%This function renames the iscell variable in the Fall.mat file to isCell.
%The Fall.mat file is generated by the Suite2p.

[fileName filePath] = uigetfile;

cd(filePath)

load(fileName)

isCell = iscell;
save(fileName, '-regexp', '^(?!fileName|filePath|iscell|eventdata|hObject|handles$).')